apiVersion: resourcecontrollerv2.ibmcloud.crossplane.io/v1alpha1
kind: ResourceInstance
metadata:
  name: mypostgres-via-crossplane
spec:
  forProvider:
    name: mypostgres-via-crossplane
    target: us-south
    resourceGroupName: default
    serviceName: databases-for-postgresql
    resourcePlanName: standard
    tags:
      - crossplane
      - caine
    parameters:
      members_disk_allocation_mb: 32768
  providerConfigRef:
    name: ibm-cloud