apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: apps.crossplane.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  claimNames:
    kind: AppClaim
    plural: appclaims
  connectionSecretKeys:
  - uri
  defaultCompositeDeletePolicy: Background
  defaultCompositionRef:
    name: cngp-service
  defaultCompositionUpdatePolicy: Automatic
  group: crossplane.io
  names:
    kind: App
    plural: apps
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.host
      name: host
      type: string
    name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              id:
                description: ID of this application that other objects will use to
                  refer to it.
                type: string
              parameters:
                properties:
                  host:
                    description: The host address of the application
                    type: string
                  image:
                    description: The container image of the application
                    type: string
                  namespace:
                    default: default
                    description: The container image of the application
                    type: string
                  port:
                    default: 80
                    description: The application port
                    type: integer
                required:
                - image
                type: object
            required:
            - id
            - parameters
            type: object
          status:
            properties:
              host:
                description: The host address of the application
                type: string
            type: object
        type: object
    served: true
