apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  creationTimestamp: "2024-03-21T16:10:39Z"
  labels:
    type: database
  name: cngp-service
spec:
  compositeTypeRef:
    apiVersion: crossplane.io/v1alpha1
    kind: App
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        environment: null
        kind: Resources
        patchSets:
          - name: metadata
            patches:
              - fromFieldPath: metadata.labels
                type: FromCompositeFieldPath
        resources:
          - base:
              apiVersion: kubernetes.crossplane.io/v1alpha1
              kind: ProviderConfig
              spec:
                credentials:
                  source: InjectedIdentity
            name: kubernetes
            patches:
              - fromFieldPath: spec.id
                toFieldPath: metadata.name
                transforms:
                  - string:
                      fmt: '%s-kubernetes'
                      type: Format
                    type: string
                type: FromCompositeFieldPath
            readinessChecks:
              - type: None
          - base:
              apiVersion: kubernetes.crossplane.io/v1alpha1
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Namespace
            name: namespace
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.namespace
                toFieldPath: spec.forProvider.manifest.metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.annotations
                toFieldPath: spec.forProvider.manifest.metadata.annotations
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels
                toFieldPath: spec.forProvider.manifest.metadata.labels                
              - type: FromCompositeFieldPath
                fromFieldPath: spec.id
                toFieldPath: spec.forProvider.manifest.metadata.labels.app
              - fromFieldPath: spec.claimRef.name
                toFieldPath: spec.providerConfigRef.name
                transforms:
                  - string:
                      fmt: '%s-kubernetes'
                      # fmt: "%s-cluster-k8s-provider-config"
                      type: Format
                    type: string
            readinessChecks:
              - fieldPath: status.atProvider.manifest.status.phase
                matchString: Active
                type: MatchString
      step: patch-and-transform
  writeConnectionSecretsToNamespace: default
