apiVersion: crossplane.io/v1alpha1
kind: AppClaim
metadata:
  name: demo
spec:
  id: demo
  compositionSelector:
    matchLabels:
      type: frontend
  parameters:
    namespace: demo
    image: dbgate/dbgate:latest
    host: dbgate.127.0.0.1.nip.io
