apiVersion: nuagik.cloud/v1alpha1
kind: AppClaim
metadata:
  name: cnpg-demo
  labels:
    app-owner: nuagik
spec:
  id: cnpg-demo
  compositionSelector:
    matchLabels:
      type: frontend
  parameters:
    namespace: demo
    image: nginx:latest
    host: nginx.127.0.0.1.nip.io
